# Generated by Django 4.1.5 on 2023-02-10 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocData",
            fields=[
                (
                    "docDataId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collegeName", models.CharField(max_length=50)),
                ("courseName", models.CharField(max_length=50)),
                ("testDate", models.DateField()),
                ("admitCardReleaseDate", models.DateField()),
                ("testCity", models.CharField(max_length=50)),
                ("admitCard", models.FileField(upload_to="pdf")),
                (
                    "syllabus",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts/images"
                    ),
                ),
                (
                    "parentUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="API.usermodel",
                    ),
                ),
            ],
        ),
    ]
